/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package SystemGUI;
import System.controller.AdminController;
import System.controller.InputProductController;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author ya22y
 */
public class AdminGUI extends javax.swing.JFrame {

    /**
     * Creates new form AdminGUI
     */
    public AdminGUI() {
        initComponents();
         input= new InputGUI(this,false);
         Qte_input= new QTE_InputGUI(this,false);
        new InputProductController(input,this);
        new AdminController(this,Qte_input);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        logout = new javax.swing.JButton();
        ajouterButton = new javax.swing.JButton();
        EditButton = new javax.swing.JButton();
        SuppButton = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        ProductTabel = new javax.swing.JTable();
        jLabel2 = new javax.swing.JLabel();
        searchField = new javax.swing.JTextField();
        searchButton = new javax.swing.JButton();
        exitButton = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(0, 102, 102));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        logout.setBackground(new java.awt.Color(0, 102, 102));
        logout.setIcon(new javax.swing.ImageIcon(getClass().getResource("/System/resources/account-logout-48.png"))); // NOI18N
        logout.setBorder(null);
        logout.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                logoutActionPerformed(evt);
            }
        });
        jPanel1.add(logout, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 490, -1, -1));

        ajouterButton.setBackground(new java.awt.Color(0, 102, 102));
        ajouterButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/System/resources/add-48.png"))); // NOI18N
        ajouterButton.setBorder(null);
        ajouterButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ajouterButtonActionPerformed(evt);
            }
        });
        jPanel1.add(ajouterButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 70, -1, -1));

        EditButton.setBackground(new java.awt.Color(0, 102, 102));
        EditButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/System/resources/edit-12-48(grey).png"))); // NOI18N
        EditButton.setBorder(null);
        EditButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                EditButtonActionPerformed(evt);
            }
        });
        jPanel1.add(EditButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 200, -1, -1));

        SuppButton.setBackground(new java.awt.Color(0, 102, 102));
        SuppButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/System/resources/delete-48(grey).png"))); // NOI18N
        SuppButton.setBorder(null);
        jPanel1.add(SuppButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 340, -1, -1));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 130, 600));

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));
        jPanel2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jPanel2MouseEntered(evt);
            }
        });
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        ProductTabel.setFont(new java.awt.Font("Ubuntu", 1, 15)); // NOI18N
        ProductTabel.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Code", "Nom", "Catégorie", "Quantité", "Description"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.String.class, java.lang.Object.class, java.lang.Integer.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        ProductTabel.setFillsViewportHeight(true);
        ProductTabel.setGridColor(new java.awt.Color(0, 102, 102));
        ProductTabel.setRowHeight(30);
        ProductTabel.setSelectionBackground(new java.awt.Color(204, 255, 255));
        ProductTabel.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        ProductTabel.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        ProductTabel.setShowGrid(true);
        ProductTabel.setShowHorizontalLines(true);
        ProductTabel.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                ProductTabelFocusGained(evt);
            }
        });
        ProductTabel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                ProductTabelMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(ProductTabel);

        jPanel2.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 190, 1090, 410));

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/System/resources/Copy of logo(1).png"))); // NOI18N
        jPanel2.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 10, 150, 90));

        searchField.setFont(new java.awt.Font("Ubuntu", 2, 18)); // NOI18N
        searchField.setForeground(new java.awt.Color(0, 102, 102));
        searchField.setText("rechercher");
        searchField.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 102, 102)));
        jPanel2.add(searchField, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 140, 270, -1));

        searchButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/System/resources/search-15-24.png"))); // NOI18N
        searchButton.setBorder(null);
        jPanel2.add(searchButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 140, -1, -1));

        exitButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/System/resources/x-mark-3-32.png"))); // NOI18N
        exitButton.setBorder(null);
        exitButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                exitButtonActionPerformed(evt);
            }
        });
        jPanel2.add(exitButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(1050, 20, -1, -1));

        getContentPane().add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 0, 1120, -1));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void logoutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_logoutActionPerformed
        
        try {
            this.setVisible(false);
            LoginGUI.launch();
            this.dispose();
        } catch (Exception ex) {
            Logger.getLogger(AdminGUI.class.getName()).log(Level.SEVERE, null, ex);
        }
        
    }//GEN-LAST:event_logoutActionPerformed

    private void ajouterButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ajouterButtonActionPerformed
      
      input.setVisible(true);
      
    }//GEN-LAST:event_ajouterButtonActionPerformed

    private void exitButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_exitButtonActionPerformed
        System.exit(0);
    }//GEN-LAST:event_exitButtonActionPerformed

    private void ProductTabelFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_ProductTabelFocusGained
         row=ProductTabel.getSelectedRow();
        selected=getSelected();
        System.out.println(selected);
    }//GEN-LAST:event_ProductTabelFocusGained

    private void EditButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_EditButtonActionPerformed
       
       if(selected!=null) Qte_input.setVisible(true);
    }//GEN-LAST:event_EditButtonActionPerformed

    private void ProductTabelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ProductTabelMouseClicked
       row=ProductTabel.getSelectedRow();
        selected=getSelected();
    }//GEN-LAST:event_ProductTabelMouseClicked

    private void jPanel2MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel2MouseEntered
       if(selected !=null){
           SuppButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/System/resources/delete-48.png")));
        EditButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/System/resources/edit-12-48.png")));
      }else{
          
          SuppButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/System/resources/delete-48(grey).png")));
        EditButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/System/resources/edit-12-48(grey).png")));
      }
    }//GEN-LAST:event_jPanel2MouseEntered

    public String getSelected(){
        return ProductTabel.getModel().getValueAt(row, 0).toString();
    }
    
     public void showAllProduct(Object[] rowModel){
        DefaultTableModel model=(DefaultTableModel)ProductTabel.getModel();
               model.addRow(rowModel);
   }
   
     private Integer row=null;
     public String selected=null;
     private InputGUI input;
     private QTE_InputGUI Qte_input;
    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JButton EditButton;
    public javax.swing.JTable ProductTabel;
    public javax.swing.JButton SuppButton;
    private javax.swing.JButton ajouterButton;
    private javax.swing.JButton exitButton;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JButton logout;
    public javax.swing.JButton searchButton;
    public javax.swing.JTextField searchField;
    // End of variables declaration//GEN-END:variables
}
