/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JDialog.java to edit this template
 */
package SystemGUI;

/**
 *
 * @author ya22y
 */
public class InputGUI extends javax.swing.JDialog {

    /**
     * Creates new form DataInputGUI
     */
    public InputGUI(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jSeparator6 = new javax.swing.JSeparator();
        jPanel1 = new javax.swing.JPanel();
        nameTextfield = new javax.swing.JTextField();
        qteTextfield = new javax.swing.JTextField();
        addButton = new javax.swing.JButton();
        jSeparator5 = new javax.swing.JSeparator();
        jSeparator8 = new javax.swing.JSeparator();
        jSeparator9 = new javax.swing.JSeparator();
        description = new javax.swing.JTextField();
        exitButton = new javax.swing.JButton();
        catTextfield = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setUndecorated(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(0, 102, 102));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        nameTextfield.setBackground(new java.awt.Color(0, 102, 102));
        nameTextfield.setFont(new java.awt.Font("Ubuntu", 0, 18)); // NOI18N
        nameTextfield.setForeground(new java.awt.Color(255, 255, 255));
        nameTextfield.setText("Nom");
        nameTextfield.setBorder(null);
        nameTextfield.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                nameTextfieldKeyTyped(evt);
            }
        });
        jPanel1.add(nameTextfield, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 60, 123, -1));

        qteTextfield.setBackground(new java.awt.Color(0, 102, 102));
        qteTextfield.setFont(new java.awt.Font("Ubuntu", 0, 18)); // NOI18N
        qteTextfield.setForeground(new java.awt.Color(255, 255, 255));
        qteTextfield.setText("Quantité");
        qteTextfield.setBorder(null);
        qteTextfield.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                qteTextfieldKeyTyped(evt);
            }
        });
        jPanel1.add(qteTextfield, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 60, 80, -1));

        addButton.setBackground(new java.awt.Color(0, 102, 102));
        addButton.setFont(new java.awt.Font("Ubuntu", 1, 24)); // NOI18N
        addButton.setForeground(new java.awt.Color(255, 255, 255));
        addButton.setText("ADD");
        jPanel1.add(addButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(245, 239, -1, -1));
        jPanel1.add(jSeparator5, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 90, 90, 18));
        jPanel1.add(jSeparator8, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 90, 137, 18));
        jPanel1.add(jSeparator9, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 90, 150, 18));

        description.setBackground(new java.awt.Color(0, 102, 102));
        description.setFont(new java.awt.Font("Ubuntu", 2, 16)); // NOI18N
        description.setForeground(new java.awt.Color(255, 255, 255));
        description.setText("Description...");
        jPanel1.add(description, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 140, 490, 80));

        exitButton.setBackground(new java.awt.Color(0, 102, 102));
        exitButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/System/resources/x-mark(white).png"))); // NOI18N
        exitButton.setBorder(null);
        exitButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                exitButtonActionPerformed(evt);
            }
        });
        jPanel1.add(exitButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 20, -1, -1));

        catTextfield.setBackground(new java.awt.Color(0, 102, 102));
        catTextfield.setFont(new java.awt.Font("Ubuntu", 2, 18)); // NOI18N
        catTextfield.setForeground(new java.awt.Color(255, 255, 255));
        catTextfield.setText("Catégorie");
        catTextfield.setBorder(null);
        jPanel1.add(catTextfield, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 60, 150, -1));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 590, 290));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void nameTextfieldKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_nameTextfieldKeyTyped
        checkIfString(evt);
    }//GEN-LAST:event_nameTextfieldKeyTyped

    private void qteTextfieldKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_qteTextfieldKeyTyped
        checkIfNumber(evt);
    }//GEN-LAST:event_qteTextfieldKeyTyped

    private void exitButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_exitButtonActionPerformed
      this.setVisible(false);
    }//GEN-LAST:event_exitButtonActionPerformed

   private void checkIfNumber(java.awt.event.KeyEvent evt){
        char c= evt.getKeyChar();
        if(!Character.isDigit(c)|| c==java.awt.event.KeyEvent.VK_BACK_SPACE || c== java.awt.event.KeyEvent.VK_DELETE){
           getToolkit().beep();
           evt.consume();}
    }
    
    private void checkIfString(java.awt.event.KeyEvent evt){
        char c= evt.getKeyChar();
        if(!Character.isAlphabetic(c)|| c==java.awt.event.KeyEvent.VK_BACK_SPACE || c== java.awt.event.KeyEvent.VK_DELETE){
           getToolkit().beep();
           evt.consume();
        }
    }
     
    public String[] getData(){
        return new String[]{nameTextfield.getText(),qteTextfield.getText(),
            catTextfield.getText(),description.getText()};
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JButton addButton;
    private javax.swing.JTextField catTextfield;
    private javax.swing.JTextField description;
    private javax.swing.JButton exitButton;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JSeparator jSeparator5;
    private javax.swing.JSeparator jSeparator6;
    private javax.swing.JSeparator jSeparator8;
    private javax.swing.JSeparator jSeparator9;
    private javax.swing.JTextField nameTextfield;
    private javax.swing.JTextField qteTextfield;
    // End of variables declaration//GEN-END:variables
}
